### ISSUE TITLE
Library does not consider cases in which `t` function is called directly

### ISSUE THREAD

**Issue by Nickersoft** [gilbsgilbs/babel-plugin-i18next-extract#13]
First off, love the library but couldn't help but notice one large caveat: the library won't extract strings unless the `t` function is being called as a property of an object (usually `i18n` or `i18next`. I think it could be beneficial to pass the translation function as an option too, so cases like this are considered:

```javascript
const t = await i18n.changeLanguage('es')
console.log(t('Test string'));
```

or

```javascript
i18n.changeLanguage('es', (err, t) => {
  console.log('Test string');
});
```

I was going to look into it but wasn't sure if allowing users to specify a blanket function is enough or if the way the file is parsed should be smarter so it knows the function originated from the i18next package. What are your thoughts?

**Comment by gilbsgilbs** [comment]
Hi,

That's indeed a neat suggestion. There's definitely something that should be done to detect those unhandled cases. Fun fact: that's the reason why I implemented "disable" comment hints in the first place. I wanted to give more control over what the library should or shouldn't consider as a translation key in order to open the door to fuzzier modes like the one you suggest.

However, the problem is maybe not that trivial. For instance, in such case:

```javascript
function Component({ t }) {
  return <p>{t('foo')}</p>
}

const Wrapper = withTranslation('my-namespace')(Component);
```

We do want to be 100% sure the `withTranslation` extractor will run first, even though we make a direct call to the `t` function. I'm afraid that if we implement this too naively, the fuzzy `t` extraction may come first in some corner-cases and wouldn't give a chance to `withTranslation` extractor (or another smart extractor) to handle the case. In short: we want to use this fuzzy strategy if and only if none of the previous approach have already worked. A quick and dirty solution would be to traverse the AST twice. But there must be a smarted approach.

I also reckon it should be possible to opt-out from this mode. But that shouldn't be too hard.
