### ISSUE TITLE
EExist error when running 

### ISSUE THREAD

**Issue by clementbalestrat** [gilbsgilbs/babel-plugin-i18next-extract#43]
It looks like it tries to run `mkdir` everytime before adding keys to the JSON file.

```
 Error: EEXIST: file already exists, mkdir './extractedTranslations/en'
```

So it literally just parse one page, add the key correctly and then errors while parsing the next one.

My configuration is super simple, I've got a `.babelrc` file with

```
{
  "presets": ["react-app"],
  "plugins": ["i18next-extract"]
}
```

**Comment by gilbsgilbs** [comment]
Hi,

Could you run `node --version` and check that your node version is at least 10? I am not able to reproduce this issue with node 10 and 12. I'm aware of such issues with node 8, but since it will reach end of life in less than 5 months, I'm not really willing to add support for it.

If you happen to use node 8, it's unclear to me how you were able to install this plugin because supported node engine version were properly specified in `package.json` a while ago. Could you also check that you run the latest version of the plugin (i.e. 0.2.3)?

Thanks.

**Comment by clementbalestrat** [comment]
Hi, thanks for your reply. I used to have node 10 but for some unknown reason NVM switched it back to 8. All good, working well now!
