### ISSUE TITLE
Passing namespace to withTranslation HOC doesn't work when using compose

### ISSUE THREAD

**Issue by emroussel** [gilbsgilbs/babel-plugin-i18next-extract#75]
Not sure if I'm missing something in the config, but it looks like when I wrap my components in `compose` from `recompose`, the namespace doesn't get picked up by `babel-plugin-i18next-extract`.

The code below puts the key in this translation file: `default.json`
```js
import React from 'react';
import { compose } from 'recompose';
import { withTranslation } from 'react-i18next';

const SomeComponent = ({ t }) => <div>{t('mykey')}</div>;
export const SomeComponentWrapped = compose(withTranslation('namespace1'))(SomeComponent);
```

And this code (when removing `compose`) puts it in this file: `namespace1.json`
```js
import React from 'react';
import { compose } from 'recompose';
import { withTranslation } from 'react-i18next';

const SomeComponent = ({ t }) => <div>{t('mykey')}</div>;
export const SomeComponentWrapped = withTranslation('namespace1')(SomeComponent);
```

I would expect both code snippet to put the key in the `namespace1.json` file.

**Comment by gilbsgilbs** [comment]
Composing is indeed not supported and I'm kind of on the fence about adding such feature. Sure we could support `compose` function from `recompose`, but then we would have to support `flowRight` from lodash, then `compose` from lodash FP and then custom implementations of compose and probably other very specific currying functions and so on. Even then, should we support both array and variadic version of lodash's `flowRight`?

Maybe we could try to be a little smart and just rely on a (possibly configurable) whitelist of `compose` keywords, still that sounds like a very specific use-case to me and a lot of "magic" would probably be involved to support every or even most use-cases.

I'm sure you know it, though as a workaround, you can use a [comment hint](https://i18next-extract.netlify.com/#/comment-hints?id=explicitly-use-a-namespace-for-a-key) for this:

```jsx
// i18next-extract-mark-ns-start namespace1
const SomeComponent = ({ t }) => <div>{t('mykey')}</div>;
// i18next-extract-mark-ns-stop

export const SomeComponentWrapped = compose(withTranslation('namespace1'))(SomeCompone
```

That was one of the main intentions behind comment hints by the way. Avoid blocking the user because a specific case (typically something very "runtime-ish") isn't or won't be supported by the library.

If you have any strong opinion on this, I'd be glad to hear it.

**Comment by emroussel** [comment]
Interesting, that makes sense.

It would be nice to be able to pass an option to the config that says everything in x directory should have y namespace instead of declaring that inside each file, but I think that would require changing the i18next API as well.

**Comment by culshaw** [comment]
This would really help us :)
